### ISSUE TITLE
https

### ISSUE THREAD

**Issue by VladimirIvanin** [pomeo/node-insales#29]
У магазинов, которые созданы не с insales.ru, а с http://www.insales.com/, http://www.insales.com.ua/, http://www.insales.kz/ нет SSL.
В API конкретно указан https для запросов, и из за этого файлы качаются через раз.
По хорошему все админки магазов должны работать по https, но возможно ли проверять протокол в API?

**Comment by pomeo** [comment]
Вделаю опцию на возможность включения только http.
А так изначально было http, но https я сделал для себя. Каким-то судом заблочен какой-то магазин на insales. Иногда у меня полгода работает, а иногда полгода не работает весь insales с абсолютно всеми магазинами. Пришлось перейти на https и проблем больше нет.

**Comment by VladimirIvanin** [comment]
Спасибо! 
По возможности на выходных обновишь пакет в npm?
Я накосячил с '/', файлы не качаются.

**Comment by pomeo** [comment]
Сегодня сделаю и опцию для http добавлю и npm обновлю

**Comment by pomeo** [comment]
```
const insales = InSales({
  id: 'your app id',
  secret: 'your app secret',
  http: true
});
```

будут запросы через http
