### ISSUE TITLE
Не запускается версия 2.0.4

### ISSUE THREAD

**Issue by VladimirIvanin** [pomeo/node-insales#35]
Модуль опубликовался с файлом index.js
![изображение](https://user-images.githubusercontent.com/15268753/218133644-b5feba7c-c9c7-4f5f-bb9f-795e9aed88af.png)

Такую ошибку выдаёт
![изображение](https://user-images.githubusercontent.com/15268753/218133731-470026b8-2a0b-4ecf-9ecc-46e9c5f8816f.png)

**Comment by pomeo** [comment]
Перезалил, prepublish не сработал
